### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by breun** [spring-cloud/spring-cloud-openfeign#1043]
On https://spring.io/projects/spring-cloud-openfeign#learn there are two broken links:

* 4.1.3 links to https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/, which shows the documentation for version 4.0.6.
* 4.1.4-SNAPSHOT links to https://docs.spring.io/spring-cloud-openfeign/docs/4.1.4-SNAPSHOT/reference/html/, which returns 404 Not Found.

For 4.1.x versions the correct link format seems to be https://docs.spring.io/spring-cloud-openfeign/reference/${version}, because these work:

* 4.1.3: https://docs.spring.io/spring-cloud-openfeign/reference/4.1.3
* 4.1.4-SNAPSHOT: https://docs.spring.io/spring-cloud-openfeign/reference/4.1.4-SNAPSHOT

**Comment by ryanjbaxter** [comment]
This should be fixed once the site updates

**Comment by breun** [comment]
When is the site expected to be updated? Currently these links are not fixed yet.

**Comment by ryanjbaxter** [comment]
It should be fixed in a few minutes, I forgot to hit the publish button 🤦‍♂️
